apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: testing
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090